require('plugins-config/nvim-tree-config')
require('plugins-config/bufferline-config')
require('plugins-config/toggleterm-config')
require('plugins-config/catppuccin-config')
require('plugins-config/lsp-config')
